# Generated by Django 5.2.1 on 2025-05-27 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('email_empresa', models.EmailField(max_length=254, unique=True)),
                ('nome_empresa', models.CharField(max_length=50)),
                ('local', models.CharField()),
                ('cpf', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=120)),
                ('contato_empresa', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('descricao', models.TextField()),
                ('senha_empresa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('sobrenome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.TextField(verbose_name=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='curriculos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculos', to='app_starhub.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('horario', models.DateTimeField()),
                ('bolsa', models.FloatField()),
                ('local', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='app_starhub.empresa')),
            ],
        ),
    ]
