# Generated by Django 5.2.1 on 2025-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_starhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='contato_empresa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
