# Generated by Django 5.2.1 on 2025-05-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_starhub', '0002_alter_empresa_contato_empresa_alter_empresa_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='horario',
            field=models.TimeField(),
        ),
    ]
