# Generated by Django 5.2.1 on 2025-05-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_starhub', '0003_alter_vaga_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contato',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
