# Generated by Django 5.2.1 on 2025-05-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_starhub', '0004_usuario_contato_usuario_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='descricao',
            new_name='descricao_empresa',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
