# Generated by Django 5.2.1 on 2025-05-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_starhub', '0005_rename_descricao_empresa_descricao_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
