# Generated by Django 5.2.1 on 2025-05-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_starhub', '0006_alter_usuario_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
